theme = 'ferale'
baseURL = 'https://liminalmarks.com/'
languageCode = "en-ca"
title = 'Ferale liminal marks'
author = "Julie Docteur"
copyright = "Copyright © 20024, Julie Docteur; all rights reserved."
DefaultContentLanguage = "en"

[menu]

  [[menu.main]]
    identifier = "bio"
    name = "Bio"
    url = "/bio/"
    weight = 1
  [[menu.main]]
    identifier = "tattoo"
    name = "Tattoo"
    url = "/tattoo/"
    weight = 3
  [[menu.main]]
    identifier = "rates"
    name = "Rates"
    url = "/rates/"
    weight = 4
  [[menu.main]]
    identifier = "shamanic-healing"
    name = "Shamanic healing"
    url = "/shamanic-healing/"
    weight = 5
  [[menu.main]]
    identifier = "testimonials"
    name = "Testimonials"
    url = "/testimonials/"
    weight = 6
  [[menu.main]]
    identifier = "thoughts"
    name = "Thoughts"
    url = "/thoughts-and-reflections/"
    weight = 7
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 8

[markup]

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false