theme = 'feraletattoomedicine'
baseURL = 'https://example.org/'
languageCode = "en-ca"
title = 'Ferale Tattoo Medecine'
author = "Julie Docteur"
copyright = "Copyright © 20024, Julie Docteur; all rights reserved."
DefaultContentLanguage = "en"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "artwork"
    name = "Artwork"
    url = "/works/"
    weight = 2
  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 3
  [[menu.main]]
    identifier = "tattoo"
    name = "Tattoo"
    url = "/tattoo/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 8

[markup]

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false